/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Always clears the cookie, with or without a valid session.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_api_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/tickets/{ticket_id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Category */
        post: operations["set_category_api_board_tickets__ticket_id__category_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/tickets/{ticket_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_api_board_tickets__ticket_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/tickets/{ticket_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move */
        post: operations["move_api_board_tickets__ticket_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/tickets/{ticket_id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take */
        post: operations["take_api_board_tickets__ticket_id__take_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Indicators */
        get: operations["get_indicators_api_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentHealth */
        AgentHealth: {
            /** Classified */
            classified: number;
            /** Corrected */
            corrected: number;
            /** Correctedshare */
            correctedShare: number | null;
            /** Othershare */
            otherShare: number | null;
        };
        /** Board */
        Board: {
            /** Categories */
            categories: components["schemas"]["IdLabel"][];
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["BoardCard"][];
            };
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Requireresponsible */
            requireResponsible: boolean;
            /** Teammembers */
            teamMembers: components["schemas"]["IdName"][];
            /** Triagecount */
            triageCount: number;
        };
        /** BoardCard */
        BoardCard: {
            /** Categoryid */
            categoryId: number | null;
            /** Categorylabel */
            categoryLabel: string | null;
            /**
             * Column
             * @enum {string}
             */
            column: "resolved_by_bot" | "awaiting_human" | "in_progress" | "resolved_by_human" | "no_response";
            /** Conversationid */
            conversationId: number;
            /** Conversationurl */
            conversationUrl: string;
            /** Id */
            id: number;
            /**
             * Lastmovedat
             * Format: date-time
             */
            lastMovedAt: string;
            /** Responsiblename */
            responsibleName: string | null;
            /** Summary */
            summary: string;
            /** Unitname */
            unitName: string | null;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Categoryid */
            categoryId: number | null;
            /** Count */
            count: number;
            /** Label */
            label: string | null;
        };
        /** CategoryIn */
        CategoryIn: {
            /** Categoryid */
            categoryId: number;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** FaqHealth */
        FaqHealth: {
            /** Faqitemid */
            faqItemId: number;
            /** Resolved */
            resolved: number;
            /** Resolvedshare */
            resolvedShare: number | null;
            /** Title */
            title: string;
            /** Used */
            used: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
        };
        /** Heatmap */
        Heatmap: {
            /** Categories */
            categories: components["schemas"]["IdLabel"][];
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
            /** Units */
            units: components["schemas"]["HeatmapUnit"][];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /** Categoryid */
            categoryId: number;
            /** Count */
            count: number;
            /** Unitid */
            unitId: number;
        };
        /** HeatmapUnit */
        HeatmapUnit: {
            /** Attendants */
            attendants: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** IdLabel */
        IdLabel: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** IdName */
        IdName: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** Indicators */
        Indicators: {
            agentHealth: components["schemas"]["AgentHealth"];
            /** Faqhealth */
            faqHealth: components["schemas"]["FaqHealth"][];
            heatmap: components["schemas"]["Heatmap"];
            outcomes: components["schemas"]["Outcomes"];
            time: components["schemas"]["TimeStats"];
            volume: components["schemas"]["Volume"];
        };
        /** IndicatorsQueryOut */
        IndicatorsQueryOut: {
            /** Fromdate */
            fromDate: string;
            /** Normalize */
            normalize: boolean;
            /** Todate */
            toDate: string;
            /** Unitid */
            unitId: number | null;
        };
        /** IndicatorsResponse */
        IndicatorsResponse: {
            data: components["schemas"]["Indicators"];
            query: components["schemas"]["IndicatorsQueryOut"];
            /** Units */
            units: components["schemas"]["IdName"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** User */
            user: string;
        };
        /** MeOut */
        MeOut: {
            /** User */
            user: string;
        };
        /** MoveIn */
        MoveIn: {
            /**
             * To
             * @enum {string}
             */
            to: "resolved_by_bot" | "awaiting_human" | "in_progress" | "resolved_by_human" | "no_response";
        };
        /** Outcomes */
        Outcomes: {
            /** Botresolutionrate */
            botResolutionRate: number | null;
            /** Bycolumn */
            byColumn: {
                [key: string]: number;
            };
            /** Byhandoffreason */
            byHandoffReason: components["schemas"]["ReasonCount"][];
            /** Identifiedreached */
            identifiedReached: number;
            /** Noresponseshare */
            noResponseShare: number | null;
        };
        /** PeriodCount */
        PeriodCount: {
            /** Count */
            count: number;
            /** Period */
            period: string;
        };
        /** ReasonCount */
        ReasonCount: {
            /** Count */
            count: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "human_requested" | "faq_not_resolved" | "no_faq_match" | "unidentified" | "registration_mismatch" | "off_topic" | "media" | "llm_failure";
        };
        /** TakeIn */
        TakeIn: {
            /** Responsibleid */
            responsibleId: number | null;
        };
        /** TimeStats */
        TimeStats: {
            /** Timetocloseavgmin */
            timeToCloseAvgMin: number | null;
            /** Timetoclosemedianmin */
            timeToCloseMedianMin: number | null;
            /** Waittotakeavgmin */
            waitToTakeAvgMin: number | null;
            /** Waittotakemedianmin */
            waitToTakeMedianMin: number | null;
        };
        /** UnitCount */
        UnitCount: {
            /** Count */
            count: number;
            /** Unitid */
            unitId: number | null;
            /** Unitname */
            unitName: string | null;
        };
        /** Volume */
        Volume: {
            /** Bycategory */
            byCategory: components["schemas"]["CategoryCount"][];
            /** Bymonth */
            byMonth: components["schemas"]["PeriodCount"][];
            /** Byunit */
            byUnit: components["schemas"]["UnitCount"][];
            /** Byweek */
            byWeek: components["schemas"]["PeriodCount"][];
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_board_api_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    set_category_api_board_tickets__ticket_id__category_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    close_api_board_tickets__ticket_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    move_api_board_tickets__ticket_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    take_api_board_tickets__ticket_id__take_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_indicators_api_indicators_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                unit?: string | null;
                norm?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
